graph_size: 100
node_dim: 2
encoder_type: revmha
decoder_type: DecoderForLarge
decoder_dim: 128
embedding_dim: 128
n_layers: 6
group_size: 100
add_init_projection: true
n_heads: 8
tanh_clipping: 50
total_epoch: 100
epoch_size: 100000
val_size: 10000
train_batch_size: 64
val_batch_size: 128
learning_rate: 0.0001
weight_decay: 1.0e-06
data_distribution: uniform
seed: 1234
gpus:
- 0
- 1
- 2
- 3
precision: 16-mixed
val_type: x8Aug_nTraj
default_run_name: TSP-N100G100-Erevmha-Txy_sum-1231T0517
wandb: false
wandb_project: tsp_eAM
tensorboard: true
run_name: TSP-N100G100-Erevmha-Txy_sum-1231T0517
save_dir: ./outputs/
val_data_path: /home/FeatFormer_debug/./trained_model_and_data/data/tsp100_test_concorde.txt
data_augment: true
encoder_use_position_encoding: true
encoder_position_encoding_type: xy_sum
multi_pointer: 8
divide_std: true
add_more_query: true
multi_pointer_level: 1
load_path: null
load_checkpoint_path: ./result_ckpt/model100.ckpt
real_data: false
integer: false
sample: false
root_dir: /home/FeatFormer_debug/./outputs/TSP-N100G100-Erevmha-Txy_sum-1231T0517
